workflows:
  release-workflow:
    name: Build APK and AAB
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Post-clone – Create missing Android folder and get packages
        script: |
          #!/bin/sh
          set -e
          set -x
          flutter create .
          flutter pub get

      - name: Build release APK
        script: flutter build apk --release

      - name: Build release App Bundle
        script: flutter build appbundle --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab



